### ISSUE TITLE
add maven support

### ISSUE THREAD

**Issue by wsdjeg** [gitskarios/Gitskarios-core#1]
i am tring to add maven support,can you give me the groupId artifactId version of this core lib

**Comment by alorma** [comment]
Wow, you are so fast!

compile 'com.github.alorma:gitskarios.-core:1.0.0'

I  just uploaded to bintray, it should be maven way too, can you check?

**Comment by wsdjeg** [comment]
greate  i have got it

**Comment by alorma** [comment]
I added you to gitskarios organization, so you don't need to fork the project.

Just download it, and work in PullRequest way :)

**Comment by wsdjeg** [comment]
thank you

**Comment by alorma** [comment]
Just to know.

What are you doing with github sdk?

And... are you  member of github development team?

**Comment by wsdjeg** [comment]
sorry i am not in the team, i now just begin to change from javaee to android

**Comment by wsdjeg** [comment]
the pom.xml @bernatborrasscm added,i have tried, it will build success

**Comment by alorma** [comment]
great!!!!!

**Comment by alorma** [comment]
@bernatborrasscm it's my company username :P

**Comment by wsdjeg** [comment]
oh i see, now i will add some to the readme ,because many of the dependency of android ,we need  add to ~/.m2 manually

**Comment by alorma** [comment]
ok thanks
