### ISSUE TITLE
Error:Failed to resolve: com.github.alorma:gitskarios-core:2.0.1

### ISSUE THREAD

**Issue by Meisolsson** [gitskarios/Gitskarios-core#5]
I can't find the version on Bintray either.

**Comment by alorma** [comment]
Hi.

Can you check now? JCenter abrobed the new version

**Comment by Meisolsson** [comment]
Still only version 1.2.0

**Comment by alorma** [comment]
I just published the `2.1.0` version. Can you check if it's available?
